# Generated by Django 5.2.17 on 2026-09-24 11:58

import apps.catalog.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('pcs', 'pcs')], max_length=3)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('unit__in', ['g', 'ml', 'pcs'])), name='catalog_ingredient_valid_unit')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('cooking_time_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('base_servings', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('meal_types', models.JSONField(validators=[apps.catalog.validators.validate_meal_types])),
                ('steps', models.JSONField(validators=[apps.catalog.validators.validate_steps])),
                ('is_active', models.BooleanField(default=False)),
                ('kcal_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_g_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs_g_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_price_rub_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cooking_time_minutes__gt', 0)), name='catalog_time_gt_0'), models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='catalog_difficulty_1_5'), models.CheckConstraint(condition=models.Q(('base_servings__gt', 0)), name='catalog_servings_gt_0'), models.CheckConstraint(condition=models.Q(('kcal_per_serving__gte', 0), ('kcal_per_serving__isnull', True), _connector='OR'), name='catalog_kcal_per_serving_nonnegative'), models.CheckConstraint(condition=models.Q(('protein_g_per_serving__gte', 0), ('protein_g_per_serving__isnull', True), _connector='OR'), name='catalog_protein_g_per_serving_nonnegative'), models.CheckConstraint(condition=models.Q(('fat_g_per_serving__gte', 0), ('fat_g_per_serving__isnull', True), _connector='OR'), name='catalog_fat_g_per_serving_nonnegative'), models.CheckConstraint(condition=models.Q(('carbs_g_per_serving__gte', 0), ('carbs_g_per_serving__isnull', True), _connector='OR'), name='catalog_carbs_g_per_serving_nonnegative'), models.CheckConstraint(condition=models.Q(('estimated_price_rub_per_serving__gte', 0), ('estimated_price_rub_per_serving__isnull', True), _connector='OR'), name='catalog_estimated_price_rub_per_serving_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_lines', to='catalog.recipe')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='catalog_quantity_gt_0'), models.UniqueConstraint(fields=('recipe', 'ingredient'), name='catalog_unique_recipe_ingredient')],
            },
        ),
    ]
